### ISSUE TITLE
Respect the browser's preference for reduced motion

### ISSUE THREAD

**Issue by Jak2k** [LordSteini/wp-marquee-news#1]

**Comment by LordSteini** [comment]
Would you provide a little bit more context, please?

**Comment by LordSteini** [comment]
I asked the Famous AI-Chatbot ChatGPT to explain what you could have wanted to say with this ticket. 
Its response was:

The statement "Respect the browser's preference for reduced motion" refers to a design and accessibility recommendation. It means that websites and web applications should respect the user’s preference to reduce motion, which many operating systems and browsers expose via the prefers-reduced-motion setting.

In your GitHub repository wp-marquee-news, which seems to be a WordPress plugin for marquee-style news tickers (scrolling or moving text elements), the person might be pointing out that your animations (like scrolling text) disregard this user preference.

What does prefers-reduced-motion mean?
Browser Support: Modern browsers provide an option for users with sensory sensitivities or other needs to reduce animations. This is communicated through the prefers-reduced-motion setting, which can be detected in CSS or JavaScript.
Problem with Animations: Animated content (like a moving marquee) can be distracting or even physically harmful for some users (e.g., those with vestibular disorders).
What is expected from you?
The person who created the issue may expect your plugin to:

- Detect the presence of the prefers-reduced-motion setting.
- Disable or alter animations accordingly when this preference is active.


My answer to this:
Because I just see no personal use to add this and I guess if needed you could easily add this by yourself, this sadly will not be added.
